# Site settings
title: "HRI FACTORY"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "HRI FACTORY"
resume_title:                   "Engineer of AI and Bioinformatics's thinking"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hghkdfbdl@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82)010-3285-6842"
resume_contact_address:         "Dong Eui University"

resume_header_contact_info:     "Dong Eui University • +82)010-3285-6842 • hghkdfbdl@ygmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>'생각하는 대로 살지 않으면 사는 대로 생각하게 된다.' 성장하는 fast follower, 끊임 없이 사고하는 Self-Motivator, 따뜻한 AI, 엔지니어 황류이의 사유하는 공간입니다.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ryuihwang/resume-template"
  # resume_twitter_url:           "http://twitter.com/ryuihwang"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
